### ISSUE TITLE
Docker image missing directories

### ISSUE THREAD

**Issue by Heartnett** [r3-team/r3#43]
### Description

I keep getting errors when trying to install "A Core Company" or any other app.
The app does not seem to create the required `temp` and `transfer` directories in the r3 container's `/opt/r3/data` bind mount directory.

The app only works after stopping the containers, clearing all bind mounts, and creating the `temp` + `transfer` directories.

Here is my docker-compose config
```yml
version: '3.3'

services:
    r3_db:
        image: postgres:latest
        container_name: r${R3_VERSION:-3.4.2}_db
        restart: always
        environment:
            POSTGRES_PASSWORD: app
            POSTGRES_USER: app
        volumes:
            - ./data:/var/lib/postgresql/data
    r3:
        build:
            context: https://github.com/r3-team/r3_docker.git#main
            args:
                r3_db_host: r3_db
                r3_os_arch: x64
                r3_version: ${R3_VERSION:-3.4.2}
                im_policy: /etc/ImageMagick-6/policy.xml
        container_name: r${R3_VERSION:-3.4.2}_app
        image: "r3/${R3_VERSION:-3.4.2}"
        depends_on:
            - r3_db
        ports:
            - "14000:80"
        restart: always
        volumes:
            - ./data_app:/opt/r3/data
            
```

### Steps to Reproduce Issue

- Create an empty folder somewhere.
- Create the docker-compose.yml file.
- Inside your terminal / command-line run `docker compose up`

### Screenshots

No `temp` directory.
![image](https://github.com/r3-team/r3/assets/11403655/a924084c-1f44-4b3e-94a7-6b4a2932f4be)

...after creating the `temp` directory, refreshing localhost in the browser, and retrying the Core Company installation...
![image](https://github.com/r3-team/r3/assets/11403655/a5e798d2-e62d-4637-8b06-e1f8dc526db7)

### Additional Info

**Operating System:** Windows 11 Pro x64 Version 22H2 Build 22621.1992
**Container Engine:** Docker version 24.0.2, build cb74dfc
